version: '3.7'

services:
  frontend:
    build: ./frontend
    # command: npm run serve
    volumes:      
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8081:8080
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgres_data: 
